### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by rishabhpoddar** [fauna/faunadb-js#341] opened 2020-09-19 12:40 UTC
This is specifically for using this package in NodeJS.

Version of package: `^3.0.1`

NodeJS version: `v13.11.0`

Operating System: MacOS 10.15.6

Version of TypeScript: `3.8.3`

Error:
```
../node_modules/faunadb/src/types/Client.d.ts:15:18 - error TS2304: Cannot find name 'fetch'.

15   fetch?: typeof fetch
```

**Comment by dwlizlo** [comment] 2020-11-05 20:51
As a workaround, you can use the solution below. It will lie to the compiler in a sense, so remember to remove it once the issue is fixed.

```
"compilerOptions": {
        "lib": [ "dom" ],
   }
```

**Comment by parkhomenko** [comment] 2021-02-24 15:24
@rishabhpoddar @dwlizlo 
Your issue should be fixed in the latest version of the driver.

**Closed** 2021-03-03 14:02 UTC
