### ISSUE TITLE
Revisit PasalCase?

### ISSUE THREAD

**Issue by ChrisTalman** [fauna/faunadb-js#171] opened 2018-11-07 19:04 UTC
Can we please revisit the matter of `PascalCase` versus `lowerCamelCase`?

It was originally raised by @alexeygolev in #100, but I don't think that the motivation to '*unify the feel of the drivers across languages*' is ultimately worthwhile to justify `PascalCase` over `lowerCamelCase`.

FaunaDB is not the first project to have drivers in multiple languages. In many other projects, they opt to conform to the idioms of each language. For instance, RethinkDB has four official language drivers for its ReQL query language - JavaScript, Python, Ruby, and Java - and each conform to the idioms of their language. There's no doubt that you're writing ReQL in each case, and its concepts remain reasonably consistent for each. It's not clear why Fauna should be any different.

It's also important to consider that Fauna does not exist in a vacuum. The driver is going to be interspersed amongst other JavaScript code and libraries, the majority of which use `lowerCamelCase`. Thus, the coding style will be inescapably inconsistent, which is disorientating.

It's also unclear who benefits from having a 'unified feel' across languages. The people most likely to use a JavaScript library are JavaScript developers, who will be well-acquainted with `lowerCamelCase`. Further, even if a non-JavaScript developer were to view a JavaScript Fauna query and attempt to understand it, identifier casing is a minor confusion compared with the confusion of understanding aspects of JavaScript syntax which Fauna can't control, like `async` and arrow functions. I do not see any reason why `lowerCamelCase` would prevent someone from understanding a JavaScript Fauna query. The Fauna query language shines through, regardless of identifier casing.

Although I did not see this mentioned in the previous discussion, I can understand how using `lowerCamelCase` could entail a somewhat greater cost in maintenance of the driver and related documentation. However, I would feel that this is the sort of matter where you bear the cost to reap the benefits of having happier and more comfortable developers. Again, other projects seem to have made that calculation and deemed it worthwhile.

Ultimately, the query language is a really critical component of a database. It's the language through which the developer communicates with the database. It's the most tangible manifestation of the database for them. So, it's important that it works well for them, and that they're comfortable using it. Currently, `PascalCase` might well put off quite a few developers, and as said here, there does not seem to be much reason to do this in the grand scheme of things.

**Comment by wcastand** [comment] 2018-11-29 17:24
Hey, i was looking for a database service to couple with lambda like now in node.
And Fauna seems like the best options right now to me, but looking at your example, do you have any plan to make your query language more readable ?

I guess PascalCase is one of the reason i feel really bad about the query language right now but also the "function call hell" is very unsettling i'd say.

```js
client.query(
  q.Replace(
    q.Ref(q.Class("posts"), "192903209792046592"),
    { data: { title: "My dog and other marvels" } }))
.then((ret) => console.log(ret))
```

this doesn't look great and it's a simple example, a real world query will be so complication with all those fn called, look like a callback hell with just functions.

Are you planning an abstractions above your query system to make it easier to use.
Maybe something like graphql query in template strings for example like gql packages ?

I probably sound like a jerk right now and i'm sorry for that, i just feel like i would use this products but right now i won't just because of how bad i feel about using this query system.

If you're interested, i would like to maybe help and find an alternative to this query API (a abstraction maybe like a babel plugins).

This project looks really interesting and promising, and seems like a great combination with lambda and serverless app using services like AWS or now.

**Comment by alexeygolev** [comment] 2019-09-18 11:49
@wcastand I understand the confusion when compared to say MongoDB node driver. But I would like to point out that the way FaunaDB does it is actually less "callback hell"-y than the the MongoDB one. 

GraphQL is implemented now as a way to query the database on the actual database layer so if that's more to your liking then luckily you can do it now.

@ChrisTalman As for the query language and the javascript driver I think my original thinking and the overall animosity towards the current implementation comes from us being so used to the way the other drivers do it (mongo, rethinkdb, ...). Normally we don't have so much of a DSL. The drivers have this pseudo-lodash api design where you chain methods to get what you want. The last call of the chain would be something that will actually execute the query. 

FaunaDB provides a DSL to write a query with values and expressions defined. And it doesn't hide the fact that you are not actually executing anything, not filtering anything or deleting anything. You're building a query expression that you can execute at a certain point as an effectful computation. So the actual approach is simplified as you don't need to know every "method" that can end your chain and fire the query. 

As a result of this, or rather to make it even more clear, the value constructors are capitalised. If you were to "camel case" them they would be `createReplace`, `createLambda`, `createFilter`, etc because they don't actually filter — they create a value of type say `Filter` that when parsed by the DSL parser will turn into something that FaunaDB understands. So it's more akin to SQL (another DSL) than to something we're used to with MongoDB.

So as much as I believe in conventions of a particular community the semantics of what this driver's functions are justify the unconventional choice of casing. It's a compromise between `createReplace` and `new Replace` and I think not a very bad one.

As for making the API closer to say MongoDB, I'd say it would be a regression:)

**Comment by danieltodonnell** [comment] 2019-10-19 05:56
There is so much great information here.  We are going to revisit this topic int he next few weeks and make some decisions about out future code formatting.

**Comment by BrunoQuaresma** [comment] 2019-12-04 13:04
Closing this for now.

**Closed by BrunoQuaresma** 2019-12-04 13:04 UTC
